<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>entasca't</title>
</head>
<body>
    <div class="container max-w-7xl mx-auto mt-8">
    <div class="mb-4">
        <h1 class=" font-sans text-3xl font-bold text-cyan-700"> Llistat de tasques</h1>
        <div class="flex justify-end">
            <!-- Cajetín búsqueda -->
            <input type="search" name="llistar" placeholder="Cercar tasques" class="px-4 py-2 mr-5 rounded-md  bg-slate-50 text-cyan-700" ></input>
            <!--  botón Nueva tarea-->
            <a href="create"><input type="submit" name="crear" value="Nova tasca" class="px-4 py-2 rounded-md bg-cyan-700 text-white hover:bg-cyan-800" ></input></a>
        </div>
    </div>
    <!-- Estructura vsita principal-->
    <div class="flex flex-col">
        <div class="overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="inline-block min-w-full overflow-hidden align-middle border-b border-gray-200 shadow sm:rounded-lg">
            <table class="min-w-full">
                <thead>
                    <tr>
                    <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-cyan-800 uppercase border-b border-gray-200 bg-cyan-50">
                        Nom tasca
                    </th>
                    <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-cyan-800 uppercase border-b border-gray-200 bg-cyan-50">
                        Tasca creada per
                    </th>
                    <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-cyan-800 uppercase border-b border-gray-200 bg-cyan-50">
                        Estat de la tasca
                    </th>
                    <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-cyan-800 uppercase border-b border-gray-200 bg-cyan-50">
                        Data / Hora inici
                    </th>
                    <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-cyan-800 uppercase border-b border-gray-200 bg-cyan-50">
                        Data / Hora finalització
                    </th>
                    <th class="px-6 py-3 text-xs font-medium leading-4 tracking-wider text-left text-cyan-800 uppercase border-b border-gray-200 bg-cyan-50" colspan="3">
                        Accions
                    </th>
                    </tr>
                </thead>
            </table>
        </div>
        </div>
    </div>
    
    </div>
</body>
</html>