<!DOCTYPE html>
<html lang="es">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>entasca't</title>
    <script src="https://cdn.tailwindcss.com"></script>
  </head>
  <header>
  <div class="relative overflow-hidden bg-no-repeat bg-cover" style="background-position: 50%;background-color: #0e7490; height: 180px;">
      <div class="flex justify-center items-center h-full">
        <div class="text-center text-white px-6 md:px-12">
        <img src="../web/images/entascat.svg">
          <h4 class="text-3xl font-bold mb-6">&nbsp &nbsp feina feta no fa destorb</h4>
        </div>
      </div>
    </div>
  </div>
</header>