<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Nova tasca</title>
    <script src="https://cdn.tailwindcss.com/?plugins=forms"></script>
  </head>

  <body>
<!-- Nova tasca -->
    <div>
      <div class="flex flex-col items-center min-h-screen pt-2 bg-cyan-50 sm:justify-center sm:pt-0">
        <div class="w-full px-16 py-10 mt-6 overflow-hidden bg-white rounded-lg lg:max-w-4xl">
          <div class="mb-4">
            <h1 class=" font-sans text-3xl font-bold text-cyan-700">
              Nova tasca
            </h1>
          </div>

          <div class="w-full px-6 py-4 bg-white rounded shadow-md ring-1 ring-gray-900/10">
            <form method="POST" action="#">
              <!-- Nom tasca -->
              <div>
                <label class="block text-sm font-bold text-gray-700" for="title">
                  Nom tasca
                </label>
                <input
                  class="block w-full mt-1 border-gray-300 rounded-md shadow-sm placeholder:text-gray-400 placeholder:text-left focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  type="text" name="nomtasca" placeholder="Com es dirà la tasca" required/>
              </div>
              <!-- Tasca creada per -->
              <div>
                <label class="block text-sm pt-5 font-bold text-gray-700" for="title">
                  Tasca creada per
                </label>
                <input
                  class="block w-full mt-1 border-gray-300 rounded-md shadow-sm placeholder:text-gray-400 placeholder:text-left focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  type="text" name="nomusuari" placeholder="Qui realitzarà la tasca" required/>
              </div>
              <div>
                <label class="block text-sm pt-5 font-bold text-gray-700" for="title">
                  Estat de la tasca
                </label>
                <select
                  class="block w-full mt-1 border-gray-300 rounded-md shadow-sm placeholder:text-gray-400 placeholder:text-left focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  name="estattasca" required>
                  <option value="saab">Per fer</option>
                  <option value="opel">En progrès</option>
                  <option value="audi">Finalitzada</option>
                </select>
              </div>
              <!-- Hora inici -->
              <div>
                <label class="block text-sm pt-5 font-bold text-gray-700" for="title">
                  Data / Hora inici
                </label>
                <input
                  class="block w-full mt-1 border-gray-300 rounded-md shadow-sm placeholder:text-gray-400 placeholder:text-left focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  type="datetime-local" name="horainici" placeholder="A quina hora s'inicia la tasca" required/>
              </div>
              <!-- Hora final -->
              <div>
                <label class="block text-sm pt-5 font-bold text-gray-700" for="title">
                  Data / Hora finalització
                </label>
                <input
                  class="block w-full mt-1 border-gray-300 rounded-md shadow-sm placeholder:text-gray-400 placeholder:text-left focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                  type="datetime-local" name="horafinal" placeholder="A quina hora finalitza la tasca" />
              </div>
              <div class="flex items-center justify-start mt-4 gap-x-2">
                <button type="submit"
                  class="px-4 py-2 rounded-md bg-cyan-700 text-white hover:bg-cyan-800 text-sm font-semibold  shadow-md focus:outline-none focus:border-gray-900 focus:ring ring-gray-300">
                  Crear
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>