<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Siniestro total</title>
</head>
<body>
    <div class="flex flex-col items-center min-h-screen pt-2 bg-cyan-50 sm:justify-center sm:pt-0">
        <div class="w-full px-16 py-10 mt-6 overflow-hidden bg-white rounded-lg lg:max-w-4xl">
            <div class="container max-w-7xl mx-auto mt-8" role="alert">
                <div class="bg-rose-700 text-white font-bold rounded-t px-4 py-2">
                    Error
                </div>
                <div class="border border-t-0 border-red-400 rounded-b bg-red-100 px-4 py-3 text-red-700">
                    <p><?php echo $this->error; ?></p>
                </div>
                <!-- <div>
                    <img src="../../../web/images/notfound.jpg" alt="page not found">
                </div> -->
            </div>
        </div>
    </div>
</body>
</html>